version: "3.9"

services:
  db:
    image: postgres:13.5-alpine
    environment:
      - POSTGRES_DB=start-up-local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    container_name: "startUpPostgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s

  flyway:
    image: "flyway/flyway:8.5-alpine"
    container_name: "flyway-start-up"
    command: -url=jdbc:postgresql://db:5432/start-up-local -user=postgres -password=postgres -connectRetries=20 -placeholders.env=local migrate
    volumes:
      - ./Infra/Flyway/:/flyway/sql
    depends_on:
      - db